week: 5
topic: "9월1주차"
problems:
  - number: 1
    title: "치즈"
    platform: "BOJ"
    level: "Gold3"
    url: "https://www.acmicpc.net/problem/2638"
  - number: 2
    title: "색종이 만들기"
    platform: "BOJ"
    level: "Silver2"
    url: "https://www.acmicpc.net/problem/2630"
  - number: 3
    title: "특정한 최단경로"
    platform: "BOJ"
    level: "Gold4"
    url: "https://www.acmicpc.net/problem/1504"