week: 1
topic: 완전탐색
problems:
  - number: 1
    title: "13038. 교환학생"
    platform: "SWEA"
    level: "D3"
    url: "https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXxNn6GaPW4DFASZ"
  - number: 2
    title: "5215. 햄버거 다이어트"
    platform: "SWEA"
    level: "D3"
    url: "https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWT-lPB6dHUDFAVT"
  - number: 3
    title: "2503. 숫자야구"
    platform: "BOJ"
    level: "Silver3"
    url: "https://www.acmicpc.net/problem/2503"
  - number: 4
    title: "14888. 연산자 끼워넣기"
    platform: "BOJ"
    level: "Silver1"
    url: "https://www.acmicpc.net/problem/14888"
  - number: 5
    title: "2659. 십자카드 문제"
    platform: "BOJ"
    level: "Silver3"
    url: "https://www.acmicpc.net/problem/2659"
  - number: 6
    title: "14620. 꽃길"
    platform: "BOJ"
    level: "Silver2"
    url: "https://www.acmicpc.net/problem/14620"
