week: 2
topic: "IM/A SW역량테스트 준비"
problems:
  - number: 1
    title: "DFS와 BFS 문제"
    platform: "BOJ"
    level: "S3"
    url: "https://www.acmicpc.net/problem/1260"
  - number: 2
    title: "오목판정"
    platform: "SWEA"
    level: "D3"
    url: "https://swexpertacademy.com/main/talk/solvingClub/problemView.do?solveclubId=AZg2OLnqix_HBINp&contestProbId=AXaSUPYqPYMDFASQ&probBoxId=AZiC5zoKCNPHBINp&type=PROBLEM&problemBoxTitle=IM%EB%8C%80%EB%B9%84%EB%AC%B8%EC%A0%9C&problemBoxCnt=14"
  - number: 3
    title: "토마토"
    platform: "BOJ"
    level: "G5"
    url: "https://www.acmicpc.net/problem/7576"
  - number: 4
    title: "핀볼게임"
    platform: "SWEA"
    level: "D4"
    url: "https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRF8s6ezEDFAUo&categoryId=AWXRF8s6ezEDFAUo&categoryType=CODE&problemTitle=5650&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1"
  - number: 5
    title: "원재의 메모리복구하기"
    platform: "SWEA"
    level: "D3"
    url: "https://swexpertacademy.com/main/talk/solvingClub/problemView.do?solveclubId=AZg2OLnqix_HBINp&contestProbId=AV19AcoKI9sCFAZN&probBoxId=AZiC5zoKCNPHBINp&type=PROBLEM&problemBoxTitle=IM%EB%8C%80%EB%B9%84%EB%AC%B8%EC%A0%9C&problemBoxCnt=14"
  - number: 6
    title: "빙고"
    platform: "BOJ"
    level: "S4"
    url: "https://www.acmicpc.net/problem/2578"
  - number: 7
    title: "최적 경로"
    platform: "SWEA"
    level: "D5"
    url: "https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=5&contestProbId=AV15OZ4qAPICFAYD&categoryId=AV15OZ4qAPICFAYD&categoryType=CODE&problemTitle=&orderBy=INQUERY_COUNT&selectCodeLang=ALL&select-1=5&pageSize=10&pageIndex=1"
