name: PR Review with Gemini

permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Python env
        uses: actions/setup-python@v1
        with:
          python-version: '3.11.13'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai PyGithub

      - name: Get Git Diff
        id: git_diff
        run: |
          git fetch origin
          git diff --unified=3 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.txt
          DIFF_CONTENT=$(cat diff.txt)
          echo "Diff content length: $(wc -c < diff.txt)"
          echo "DIFF_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$DIFF_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "Diff added to GITHUB_ENV"

      - name: Run Gemini Code Review Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python3 docs/generate_review.py